name: Generate Snake

on:
  schedule: # Runs at 12 AM UTC daily
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate snake game from contributions
        uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Commit and push the SVG
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add dist/github-contribution-grid-snake.svg
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Generate snake game from contributions"
            git push origin master
          else
            echo "No changes to commit"
          fi
